name: Build

on:
  push:
    branches: [ main, experimental ]
    tags: [ "*" ]
  pull_request:
    branches: [ main, experimental ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        # Running these in a matrix allows them to build in parallel
        os: [ubuntu-latest, windows-latest, macos-14]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.7

      - name: Cache Haxelibs
        uses: actions/cache@v4
        with:
          path: |
            # Paths for Linux/Mac and Windows haxelib storage
            ~/haxelib
            C:\haxelib
          key: ${{ runner.os }}-haxelib-${{ hashFiles('project.xml', 'hmm.json') }}
          restore-keys: |
            ${{ runner.os }}-haxelib-

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install libvlc-dev libvlccore-dev -y

      - name: Install Libraries
        shell: bash
        run: |
          # Set up haxelib path based on OS
          if [ "${{ runner.os }}" = "Windows" ]; then
            haxelib setup C:/haxelib
          else
            haxelib setup ~/haxelib
          fi
          
          haxelib install hxcpp --quiet
          haxelib install hmm --quiet
          haxelib run hmm install

      - name: Compile
        shell: bash
        run: |
          if [ "${{ runner.os }}" = "Linux" ]; then
            haxelib run lime build Project.xml linux
          elif [ "${{ runner.os }}" = "Windows" ]; then
            haxelib run lime build windows
          else
            arch -x86_64 haxelib run lime build mac
          fi

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: |
            export/release/linux/bin
            export/release/windows/bin
            export/release/macos/bin